### ISSUE TITLE
how to copy folder in my repo

### ISSUE THREAD

**Issue by thelinguist** [ItsKarma/aws-cli#5]
I'm trying to figure out how to give the github action the contents of the folder I want to send to s3. When I specify the folder it returns an error saying the folder cannot be found.

Kinda new to actions, maybe I need to add something first?

script looks like: 
```yml
name: Deployment scripts

on:
  push:
    branches:
      - master
    paths:
      - 'cloud/**'

jobs:
  sendToS3:

    runs-on: ubuntu-latest

    env:
      CI: true

    timeout-minutes: 10

    steps:
      - name: AWS CLI
        uses: ItsKarma/aws-cli@v1.70.0    # https://github.com/marketplace/actions/aws-cli
        with:
          args: s3 sync --delete cloud/ s3://${{secrets.BUCKET}}/
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: "us-west-2"
```

Thanks
